 <!-- Copyright (C) 2009 The Libphonenumber Authors

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.

     @author: Shaopeng Jia

     Metadata on Phone Number Plan and formatting rules
     Note: Territories are in alphabetical order by their IDs, which are based on CLDR
           two-letter region codes (or are set to "001" for non-geographical entities, which
           represents "World" in the UN M.49 standard). The country names in the comments are the
           official short names in English according to CLDR.

     For more information on what each element represents, see
     resources/phonemetadata.proto

     Note that if you want to add validation metadata, the generalDesc nationalNumberPattern must be
     provided. If this is missing, then the country will be considered to have no more specific
     phone-number type metadata (fixedLine, mobile etc) and hence only basic validation rules
     (numbers should be between 3 and 15 digits long) will be applied.

     If adding an element for a non-geographical entity, please add an example number element to the
     general description.

     Country code, international and national prefix information main source:
     http://www.itu.int/pub/T-SP-E.164C-2011

     Known omissions:
     * French Southern Territories (id="TF" countryCode="262")
       This is not covered due to lack of information about its numbering plan. It has 140
       temporary inhabitants.

     * Pitcairn Island (id="PN")
       This is not supported since evidence seems to be that the 50 inhabitants use satellite
       phones.

     See also:
       https://github.com/google/libphonenumber/blob/master/FAQ.md#unsupported
     -->

<!DOCTYPE phoneNumberMetadata [
    <!ELEMENT phoneNumberMetadata (territories)>
    <!ELEMENT territories (territory+)>
    <!ELEMENT territory (references?, availableFormats?, generalDesc, noInternationalDialling?,
        fixedLine?, mobile?, pager?, tollFree?, premiumRate?,
        sharedCost?, personalNumber?, voip?, uan?, voicemail?)>
    <!ELEMENT references (sourceUrl+)>
    <!ELEMENT generalDesc (nationalNumberPattern)>
    <!ELEMENT noInternationalDialling (possibleLengths, nationalNumberPattern)>
    <!ELEMENT fixedLine (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT mobile (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT pager (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT tollFree (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT premiumRate (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT sharedCost (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT personalNumber (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT voip (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT uan (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT voicemail (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT sourceUrl (#PCDATA)>
    <!ELEMENT availableFormats (numberFormat+)>
    <!ELEMENT nationalNumberPattern (#PCDATA)>
    <!ELEMENT exampleNumber (#PCDATA)>
    <!ELEMENT numberFormat (leadingDigits*, format, intlFormat*)>
    <!ELEMENT format (#PCDATA)>
    <!ELEMENT intlFormat (#PCDATA)>
    <!ELEMENT leadingDigits (#PCDATA)>
    <!ELEMENT possibleLengths EMPTY>

    <!ATTLIST territory id CDATA #REQUIRED>
    <!ATTLIST territory countryCode CDATA #REQUIRED>
    <!ATTLIST territory mainCountryForCode (true) #IMPLIED>
    <!ATTLIST territory leadingDigits CDATA #IMPLIED>
    <!ATTLIST territory preferredInternationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory internationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixForParsing CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixTransformRule CDATA #IMPLIED>
    <!ATTLIST territory preferredExtnPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixFormattingRule CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixOptionalWhenFormatting (true) #IMPLIED>
    <!ATTLIST territory carrierCodeFormattingRule CDATA #IMPLIED>
    <!ATTLIST territory mobileNumberPortableRegion (true) #IMPLIED>
    <!ATTLIST possibleLengths national CDATA #REQUIRED>
    <!ATTLIST possibleLengths localOnly CDATA #IMPLIED>
    <!ATTLIST numberFormat nationalPrefixFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat nationalPrefixOptionalWhenFormatting (true) #IMPLIED>
    <!ATTLIST numberFormat carrierCodeFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat pattern CDATA #REQUIRED>
]>

<phoneNumberMetadata>
  <territories>
    <!-- Ukraine (UA) -->
    <!-- http://www.itu.int/oth/T02020000DB/en -->
    <!-- http://en.wikipedia.org/wiki/%2B380 -->
    <!-- No definitive list has been found of what constitutes the area code for formatting.
         http://www.ua.all-biz.info/guide/phonecodes is useful but not error-free.
         Have used local yellow pages guidelines, Google searches, regression tests
         and bugs to reverse-engineer the formatting rules. -->
    <territory id="UA" countryCode="380" preferredInternationalPrefix="0~0" internationalPrefix="00"
               nationalPrefix="0">
      <availableFormats>
        <!-- Fixed line -->
        <numberFormat pattern="(\d{3})(\d{3})(\d{3})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>
            6[12][29]|
            (?:
              3[1-8]|
              4[136-8]|
              5[12457]|
              6[49]
            )2|
            (?:
              56|
              65
            )[24]
          </leadingDigits>
          <leadingDigits>
            6[12][29]|
            (?:
              35|
              4[1378]|
              5[12457]|
              6[49]
            )2|
            (?:
              56|
              65
            )[24]|
            (?:
              3[1-46-8]|
              46
            )2[013-9]
          </leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <!-- Fixed line (4-digit area code). -->
        <numberFormat pattern="(\d{4})(\d{5})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>
            3[1-8]|
            4(?:
              [1367]|
              [45][6-9]|
              8[4-6]
            )|
            5(?:
              [1-5]|
              6[0135689]|
              7[4-6]
            )|
            6(?:
              [12][3-7]|
              [459]
            )
          </leadingDigits>
          <leadingDigits>
            3[1-8]|
            4(?:
              [1367]|
              [45][6-9]|
              8[4-6]
            )|
            5(?:
              [1-5]|
              6(?:
                [015689]|
                3[02389]
              )|
              7[4-6]
            )|
            6(?:
              [12][3-7]|
              [459]
            )
          </leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <!-- General format (fixed line, mobile, voip etc.) -->
        <numberFormat pattern="(\d{2})(\d{3})(\d{4})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>
            [3-7]|
            89|
            9[1-9]
          </leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <!-- Premium Rate and Toll Free -->
        <numberFormat pattern="(\d{3})(\d{3})(\d{3,4})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>[89]</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>
          [89]\d{9}|
          [3-9]\d{8}
        </nationalNumberPattern>
      </generalDesc>
      <!-- Official numbering plan https://regulation.gov.ua/documents/id89506 (Dated: 23.11.2006)
           mentions that xx[018] (xx represents valid area code) fixed-line numbers as invalid and
           we are also unable to find valid numbers online. This doc is already outdated and
           contradicted (Eg: length of NSN) by some more recent evidence. Considering the impact
           we choose not to mark those ranges as invalid. -->
      <fixedLine>
        <possibleLengths national="9" localOnly="[5-7]"/>
        <exampleNumber>311234567</exampleNumber>
        <nationalNumberPattern>
          (?:
            3[1-8]|
            4[13-8]|
            5[1-7]|
            6[12459]
          )\d{7}
        </nationalNumberPattern>
      </fixedLine>
      <!-- Added 71 prefix based on user report and 72 based on online numbers.  -->
      <mobile>
        <possibleLengths national="9"/>
        <exampleNumber>501234567</exampleNumber>
        <nationalNumberPattern>
          (?:
            39|
            50|
            6[36-8]|
            7[1-3]|
            9[1-9]
          )\d{7}
        </nationalNumberPattern>
      </mobile>
      <tollFree>
        <possibleLengths national="9,10"/>
        <exampleNumber>800123456</exampleNumber>
        <nationalNumberPattern>800[1-8]\d{5,6}</nationalNumberPattern>
      </tollFree>
      <!-- 4th digit added based on
           http://www.mts.ua/ru/support/services/200-tarify-na-nomera-0-800-0-900-0-703/ -->
      <premiumRate>
        <possibleLengths national="9,10"/>
        <exampleNumber>900212345</exampleNumber>
        <nationalNumberPattern>900[239]\d{5,6}</nationalNumberPattern>
      </premiumRate>
      <!-- 89[1-579] ranges are mentioned as "Non-geographic number – mobile services assigned" in
           the ITU doc. All the 89X phone numbers found online are listed as conference calls and
           skype calls which are actually VOIP. And also the companies to which these ranges are
           assigned (as per ITU doc) are more of VOIP service providers. So supporting them under
           VOIP. -->
      <voip>
        <possibleLengths national="9"/>
        <exampleNumber>891234567</exampleNumber>
        <nationalNumberPattern>89[1-579]\d{6}</nationalNumberPattern>
      </voip>
    </territory>

  </territories>
</phoneNumberMetadata>
